### ISSUE TITLE
Test failures in the 0.16.0 release

### ISSUE THREAD

**Issue by orhun** [lycheeverse/lychee#1513]
I'm hitting these 2 failures while building `lychee` for Arch Linux:

<details>
<summary>Details</summary>

```sh
------------
 Nextest run ID 12f79d07-8cbf-4d29-9a91-879b073c65f2 with nextest profile: default
    Starting 319 tests across 14 binaries (7 tests skipped)
        PASS [   0.679s] benches::bench/extract extract from large docs
        FAIL [   0.020s] lychee::cli cli::test_basic_auth

--- STDOUT:              lychee::cli cli::test_basic_auth ---

running 1 test
test cli::test_basic_auth ... FAILED

failures:

failures:
    cli::test_basic_auth

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 74 filtered out; finished in 0.02s


--- STDERR:              lychee::cli cli::test_basic_auth ---
thread 'cli::test_basic_auth' panicked at /usr/src/debug/rust/rustc-1.81.0-src/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=101
stderr=``````
thread \'main\' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/console-subscriber-0.4.0/src/lib.rs:262:9:
task tracing requires Tokio to be built with RUSTFLAGS=\"--cfg tokio_unstable\"!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```sh
command=`"/build/lychee/src/lychee-0.16.0/target/debug/lychee" "--verbose" "--basic-auth" "http://127.0.0.1:37767 username:password123" "-"`
stdin=`"http://127.0.0.1:37767"`
code=101
stdout=""
stderr=```
thread \'main\' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/console-subscriber-0.4.0/src/lib.rs:262:9:
task tracing requires Tokio to be built with RUSTFLAGS=\"--cfg tokio_unstable\"!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   Canceling due to test failure
        FAIL [   0.020s] lychee::cli cli::test_cache_config

--- STDOUT:              lychee::cli cli::test_cache_config ---

running 1 test
test cli::test_cache_config ... FAILED

failures:

failures:
    cli::test_cache_config

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 74 filtered out; finished in 0.02s


--- STDERR:              lychee::cli cli::test_cache_config ---
thread 'cli::test_cache_config' panicked at /usr/src/debug/rust/rustc-1.81.0-src/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=101
stderr=``````
thread \'main\' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/console-subscriber-0.4.0/src/lib.rs:262:9:
task tracing requires Tokio to be built with RUSTFLAGS=\"--cfg tokio_unstable\"!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```sh
command=`env -i "/build/lychee/src/lychee-0.16.0/target/debug/lychee" "--config" "/build/lychee/src/lychee-0.16.0/fixtures/configs/cache.toml" "-"`
stdin=`"http://127.0.0.1:43637"`
code=101
stdout=""
stderr=```
thread \'main\' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/console-subscriber-0.4.0/src/lib.rs:262:9:
task tracing requires Tokio to be built with RUSTFLAGS=\"--cfg tokio_unstable\"!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------
     Summary [   0.718s] 3/319 tests run: 1 passed, 2 failed, 0 skipped
        FAIL [   0.020s] lychee::cli cli::test_basic_auth
        FAIL [   0.020s] lychee::cli cli::test_cache_config
warning: 316/319 tests were not run due to test failure (run with --no-fail-fast to run all tests)
error: test run failed
```

</details>

Any idea about what's going on? 👀

**Comment by mre** [comment]
Thanks @orhun.
It's the console subscriber. Since I don't think anyone uses that, I'll remove it with the next release.
Propably not worth it, but if you like, you can try to disable the subscriber:

https://github.com/lycheeverse/lychee/blob/f63b4ae65b7527aa344c496dd8e6828ce90da059/lychee-bin/Cargo.toml#L82

**Comment by orhun** [comment]
Thanks for letting me know - I don't know how I missed that from the logs, skill issue I guess.

The package is now updated :)

**Comment by mre** [comment]
>  skill issue I guess

Probably. 😜

Just kidding. Thanks for maintaining the package Orhun!
